version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    volumes:
      - db_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    command: python manage.py runserver
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
