[tool.poetry]
name = "app"
version = "1.0.0"
description = ""
authors = ["mihilmy"]
license = "MIT"

[tool.poetry.dependencies]
python = ">= 3.10"
django = "^4.2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
